name: HPC_Drug
channels:
  - omnia
  - conda-forge
  - defaults
dependencies:
  - openbabel=2.4
  - gawk
  - gsl
  - numpy
  - openmm
  - openssl
  - pip
  - plumed
  - python
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - wheel
  - xdrfile
  - xz
  - zlib
  - pdbfixer
  - Cython
  - mdtraj
  - scipy
  - pip:
    - astunparse
    - biopython
    - bootstrapped
    - certifi
    - cycler
    - decorator
    - griddataformats
    - gromacswrapper
    - gsd
    - importlib-resources
    - joblib
    - kiwisolver
    - matplotlib
    - MDAnalysis>=1.1.1
    - mmtf-python
    - mock
    - msgpack
    - networkx
    - numkit
    - pillow
    - python-dateutil
    - pytz
    - tqdm
    - 'git+https://github.com/MauriceKarrenbrock/FSDAMGromacs.git'
    - 'git+https://github.com/MauriceKarrenbrock/HREMGromacs.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonAuxiliaryFunctions.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonFSDAM.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonPDBStructures.git'
    - 'git+https://github.com/prody/ProDy.git'
