name: HPC_Drug
channels:
  - omnia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - openff-toolkit
  - openbabel=2.4
  - numpy
  - openmm
  - openmmtools
  - openmmforcefields
  - pip
  - plumed
  - python
  - pdbfixer
  - mdtraj
  - scipy
  - MDAnalysis>=1.1.1
  - biopython
  - pytest
  - pytest-mock
  - parmed
  - pip:
    - astunparse
    - bootstrapped
    - certifi
    - cycler
    - decorator
    - griddataformats
    - gsd
    - joblib
    - kiwisolver
    - mmtf-python
    - msgpack
    - networkx
    - pillow
    - python-dateutil
    - pytz
    - tqdm
    - 'git+https://github.com/MauriceKarrenbrock/FSDAMGromacs.git'
    - 'git+https://github.com/MauriceKarrenbrock/HREMGromacs.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonAuxiliaryFunctions.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonFSDAM.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonPDBStructures.git'
    - 'git+https://github.com/prody/ProDy.git'
