name: HPC_Drug
channels:
  - omnia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - openbabel=2.4
  - gawk
  - gsl
  - numpy
  - openmm
  - openmmtools
  - openmmforcefields
  - openssl
  - pip
  - plumed
  - python
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - wheel
  - xdrfile
  - xz
  - zlib
  - pdbfixer
  - Cython
  - mdtraj
  - scipy
  - MDAnalysis>=1.1.1
  - biopython
  - pytest
  - pytest-mock
  - matplotlib
  - numkit
  - gromacswrapper
  - pip:
    - astunparse
    - bootstrapped
    - certifi
    - cycler
    - decorator
    - griddataformats
    - gsd
    - importlib-resources
    - joblib
    - kiwisolver
    - mmtf-python
    - msgpack
    - networkx
    - pillow
    - python-dateutil
    - pytz
    - tqdm
    - 'git+https://github.com/MauriceKarrenbrock/FSDAMGromacs.git'
    - 'git+https://github.com/MauriceKarrenbrock/HREMGromacs.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonAuxiliaryFunctions.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonFSDAM.git'
    - 'git+https://github.com/MauriceKarrenbrock/PythonPDBStructures.git'
    - 'git+https://github.com/prody/ProDy.git'
